config/routes.rb
Worstbandnames::Application.routes.draw do
  devise_for :users
  resources :bandnames do
    member do
      post 'upvote'
    end
  end

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
        can :manage, :all
    elsif user.user?
        can :create, Bandname
        can :edit, Bandname, :approved => true, :user_id => user.id
        can :destroy, Bandname, :approved => true, :user_id => user.id
        can :read, Bandname, :approved => true
        can :upvote, Bandname
    else
        can :read, Bandname, :approved => true
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities
  end
end

app/models/bandname.rb
class Bandname < ActiveRecord::Base
  belongs_to :submitter, class_name: "User"
  has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bandnames, foreign_key: "submitter"

  def admin?
    role == 'admin'
  end

  def user?
    role == 'user'
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :bandname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bandnames_controller.rb
class BandnamesController < ApplicationController
before_action :set_bandname, only: [:show, :edit, :update, :destroy, :upvote]
load_and_authorize_resource

  def new
    @bandname = Bandname.new
  end

  def create
    @bandname = Bandname.new(bandname_params)
    if @bandname.save
      flash[:notice] = "Bandname Created"
      redirect_to @bandname
    else
      flash.now[:error] = "bandname could not be saved"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @bandname.update(bandname_params)
      redirect_to @bandname
    else
      render :edit
    end
  end

  def destroy
    @bandname.destroy
    redirect_to bandnames_path
  end

  def index
  end

  def upvote
    @bandname.votes.create
    redirect_to(bandnames_path)
  end

  private

  def bandname_params
    params.require(:bandname).permit(:name)
  end

  def set_bandname
    @bandname = Bandname.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @bandnames = Bandname.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bandnames_helper.rb
module BandnamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bandnames/_form.html.erb
<%= form_for @bandname do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<%end %>

app/views/bandnames/_index.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Submitter</th>
    </tr>
  </thead>
  <tbody>

<% @bandnames.each do |bandname| %>
  <tr>
    <td><%= bandname.name %></td>
    <td><%= bandname.submitter %></td>
    <td><%= pluralize(bandname.votes.count, "vote") %></td>
    <% if can? :upvote, Bandname %>
      <td><%= button_to "+1", upvote_bandname_path(bandname), method: :post %></td>
    <% end %>
    <td><%= link_to 'Show', bandname %></td>
    <% if can? :edit, Bandname %>
      <td><%= link_to 'Edit', edit_bandname_path(bandname) %> </td>
    <% end %>
    <% if can? :destroy, Bandname %>
      <td><%= link_to 'Delete', bandname_path(bandname), method: :delete, data: {confirm: 'Are You Sure?'} %></td>
    <% end %>
  </tr>
<% end %>

app/views/bandnames/edit.html.erb
<h1>Edit Bandname</h1>

<%= render "form" %>

<%= link_to "Back", bandnames_path %>

app/views/bandnames/index.html.erb
<h1>Band Names</h1>

<% if can? :create, Bandname %>
  <%= link_to 'Submit Bandname', new_bandname_path %>
<% end %>

<%= render "index" %>

app/views/bandnames/new.html.erb
<h1>New Bandname</h1>

<%= render "form" %>

app/views/bandnames/show.html.erb
<p>Bandname: <%= @bandname.name %></p>
<p>Submitted by: <%= @bandname.submitter %></p>
<% if can? :destroy, Bandname %>
  <%= link_to 'Delete', bandname_path(@bandname), method: :delete, data: {confirm: 'Are You Sure?'} %>
<% end %>
<% if can? :edit, Bandname %>
  <%= link_to "Edit", edit_bandname_path(:bandname_id) %>
<% end %>
<%= link_to "Back", bandnames_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worstbandnames</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>
  <body>

    <% if current_user.present? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign in", user_session_path %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/welcome/index.html.erb
<h1>The Worst Band Names Ever</h1>

<%= render "bandnames/index" %>

<%= link_to 'Submit Bandname', new_bandname_path %>